user_file=open('text_6.txt', 'r', encoding='utf-8')
content=user_file.readlines()
content=''.join(content)
content=content.replace('-', '')
content=content.replace('пр', '')
content=content.replace('л', '')
content=content.replace('аб', '')
content=content.replace('()', '')
content=content.replace(':', '')
content=content.split()
content_sum_math=int(content[3])+int(content[4])
content_sum_physics=int(content[8])+int(content[9])+int(content[10])
content_sum_informatics=int(content[14])+int(content[12])+int(content[13])
content_sum_literature=int(content[17])+int(content[16])
result_dict={content[0]: content[1], content[2]: content_sum_math, content[5]: content[6], content[7]: content_sum_physics, content[11]: content_sum_informatics, content[15]: content_sum_literature, content[18]: content[19]}
print(result_dict)
user_file.close()